# Generated by Django 5.1.2 on 2024-10-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='visited_circuits',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='category',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='duration',
        ),
        migrations.AddField(
            model_name='circuit',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
