# Generated by Django 5.1.2 on 2024-10-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='difficulty_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='circuit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='circuit_images/'),
        ),
    ]
