# Generated by Django 5.1.2 on 2024-10-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0004_circuit_difficulty_level_circuit_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuit',
            name='image',
        ),
    ]
